<template>
    <section class="works-about">
        <ul class="works-about__list">
            <li class="works-about__item" v-for="(thumbnail, index) in thumbnailList()" :key="index">
                <a :href="thumbnail.link" target="_blank" rel="noopener noreferrer" class="works-about__link">
                    <figcaption class="works-about__caption">
                        <p class="works-about__date" v-html="thumbnail.day"></p>
                        <h3 class="works-about__title" v-html="thumbnail.title"></h3>
                    </figcaption>
                    <AppImageWebp :pc-img="`${thumbnail.png}`" :sp-img="`${thumbnail.pngSp}`" :pc-img-webp="`${thumbnail.webp}`" :sp-img-webp="`${thumbnail.webpSp}`" :alt="`${thumbnail.alt}`" :role="``" :width="thumbnail.width" :height="thumbnail.height" />
                </a>
            </li>
        </ul>
        <transition name="button">
            <button class="works-about__top-button" v-show="buttonActive" @click="returnTop">Page Top</button>
        </transition>
    </section>
</template>
<style lang="scss" scoped>
@import '~/assets/styles/project/works/_about';
</style>

<script lang="ts">
import Vue from 'vue';
import { WorksAll } from '~/types/worksAll';

export default Vue.extend({
    data() {
        return {
            buttonActive: false,
            scroll: 0,
            thumbnailList: (): Array<WorksAll> => [
                {
                    link: 'https://kaito-takase.dev/2d-glasses/',
                    png: '2d-glasses.png',
                    pngSp: '2d-glasses.png',
                    webp: '2d-glasses.webp',
                    webpSp: '2d-glasses.webp',
                    alt: 'Try Glasses',
                    width: 1341,
                    height: 733,
                    title: 'Try Glasses',
                    day: '2022 / 4 / 10',
                },
                {
                    link: 'https://kaito-takase.dev/face-api/',
                    png: 'face-api.png',
                    pngSp: 'face-api.png',
                    webp: 'face-api.webp',
                    webpSp: 'face-api.webp',
                    alt: '表情測定ツール',
                    width: 1341,
                    height: 733,
                    title: '表情測定ツール',
                    day: '2022 / 4 / 3',
                },
                {
                    link: 'https://kaito-takase.dev/3d-react/',
                    png: '3d-react.png',
                    pngSp: '3d-react.png',
                    webp: '3d-react.webp',
                    webpSp: '3d-react.webp',
                    alt: '3D Demo React',
                    width: 1341,
                    height: 733,
                    title: '3D Demo React',
                    day: '2022 / 4 / 2',
                },
                {
                    link: 'https://kaito-takase.dev/3d-balls/',
                    png: '3d-balls.png',
                    pngSp: '3d-balls.png',
                    webp: '3d-balls.webp',
                    webpSp: '3d-balls.webp',
                    alt: '3D Demo Balls',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Balls',
                    day: '2022 / 3 / 29',
                },
                {
                    link: 'https://kaito-takase.dev/reflexes-game/',
                    png: 'reflexes-game.png',
                    pngSp: 'reflexes-game.png',
                    webp: 'reflexes-game.webp',
                    webpSp: 'reflexes-game.webp',
                    alt: '反応速度計測ゲーム',
                    width: 1341,
                    height: 733,
                    title: '反応速度計測ゲーム',
                    day: '2022 / 3 / 6',
                },
                {
                    link: 'https://kaito-takase.dev/3d-dracoloader/',
                    png: '3d-dracoloader.png',
                    pngSp: '3d-dracoloader.png',
                    webp: '3d-dracoloader.webp',
                    webpSp: '3d-dracoloader.webp',
                    alt: '3D Demo DRACOLoader',
                    width: 1341,
                    height: 733,
                    title: '3D Demo DRACOLoader',
                    day: '2022 / 2 / 26',
                },
                {
                    link: 'https://kaito-takase.dev/3d-ice-cream/',
                    png: '3d-ice-cream.png',
                    pngSp: '3d-ice-cream.png',
                    webp: '3d-ice-cream.webp',
                    webpSp: '3d-ice-cream.webp',
                    alt: '3D Demo Ice Cream',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Ice Cream',
                    day: '2022 / 1 / 6',
                },
                {
                    link: 'https://kaito-takase.dev/2d-ice-cream/',
                    png: '2d-ice-cream.png',
                    pngSp: '2d-ice-cream.png',
                    webp: '2d-ice-cream.webp',
                    webpSp: '2d-ice-cream.webp',
                    alt: '2D Demo Ice Cream',
                    width: 1341,
                    height: 733,
                    title: '2D Demo Ice Cream',
                    day: '2022 / 1 / 6',
                },
                {
                    link: 'https://kaito-takase.dev/3d-qiita/',
                    png: '3d-qiita.png',
                    pngSp: '3d-qiita.png',
                    webp: '3d-qiita.webp',
                    webpSp: '3d-qiita.webp',
                    alt: '3D Demo Qiita',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Qiita',
                    day: '2021 / 12 / 3',
                },
                {
                    link: 'https://kaito-takase.dev/3d-room/',
                    png: '3d-room2.png',
                    pngSp: '3d-room2.png',
                    webp: '3d-room2.webp',
                    webpSp: '3d-room2.webp',
                    alt: '3D Demo Room',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Room',
                    day: '2021 / 11 / 18',
                },
                {
                    link: 'https://kaito-takase.dev/3d-soccer/',
                    png: '3d-soccer.png',
                    pngSp: '3d-soccer.png',
                    webp: '3d-soccer.webp',
                    webpSp: '3d-soccer.webp',
                    alt: '3D Demo Soccer',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Soccer',
                    day: '2021 / 11 / 12',
                },
                {
                    link: 'https://kaito-takase.dev/3d-banana-apple/',
                    png: '3d-banana-apple.png',
                    pngSp: '3d-banana-apple.png',
                    webp: '3d-banana-apple.webp',
                    webpSp: '3d-banana-apple.webp',
                    alt: '3D Demo Banana and Apple',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Banana and Apple',
                    day: '2021 / 11 / 11',
                },
                {
                    link: 'https://kaito-takase.dev/3d-ice/',
                    png: '3d-ice.png',
                    pngSp: '3d-ice.png',
                    webp: '3d-ice.webp',
                    webpSp: '3d-ice.webp',
                    alt: '3D Demo Ice',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Ice',
                    day: '2021 / 11 / 9',
                },
                {
                    link: 'https://kaito-takase.dev/3d-multiple/',
                    png: '3d-multiple.png',
                    pngSp: '3d-multiple.png',
                    webp: '3d-multiple.webp',
                    webpSp: '3d-multiple.webp',
                    alt: '3D Demo Multiple',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Multiple',
                    day: '2021 / 11 / 5',
                },
                {
                    link: 'https://kaito-takase.dev/3d-diamond/',
                    png: '3d-diamond.png',
                    pngSp: '3d-diamond.png',
                    webp: '3d-diamond.webp',
                    webpSp: '3d-diamond.webp',
                    alt: '3D Demo Diamond',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Diamond',
                    day: '2021 / 11 / 2',
                },
                {
                    link: 'https://kaito-takase.dev/3d-plane2/',
                    png: '3d-plane2.png',
                    pngSp: '3d-plane2.png',
                    webp: '3d-plane2.webp',
                    webpSp: '3d-plane2.webp',
                    alt: '3D Demo Plane',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Plane',
                    day: '2021 / 11 / 2',
                },
                {
                    link: 'https://kaito-takase.dev/3d-plane/',
                    png: '3d-plane.png',
                    pngSp: '3d-plane.png',
                    webp: '3d-plane.webp',
                    webpSp: '3d-plane.webp',
                    alt: '3D Demo ScrollTrigger',
                    width: 1341,
                    height: 733,
                    title: '3D Demo ScrollTrigger',
                    day: '2021 / 11 / 1',
                },
                {
                    link: 'https://kaito-takase.dev/3d-cushion/',
                    png: '3d-cushion.png',
                    pngSp: '3d-cushion.png',
                    webp: '3d-cushion.webp',
                    webpSp: '3d-cushion.webp',
                    alt: '3D Demo Cushion',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Cushion',
                    day: '2021 / 10 / 29',
                },
                {
                    link: 'https://kaito-takase.dev/3d-hand/',
                    png: '3d-hand.png',
                    pngSp: '3d-hand.png',
                    webp: '3d-hand.webp',
                    webpSp: '3d-hand.webp',
                    alt: '3D Demo Hand',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Hand',
                    day: '2021 / 10 / 29',
                },
                {
                    link: 'https://kaito-takase.dev/3d-earth/',
                    png: '3d-earth.png',
                    pngSp: '3d-earth.png',
                    webp: '3d-earth.webp',
                    webpSp: '3d-earth.webp',
                    alt: '3D Demo Earth',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Earth',
                    day: '2021 / 10 / 27',
                },
                {
                    link: 'https://kaito-takase.dev/3d-can/',
                    png: '3d-can.png',
                    pngSp: '3d-can.png',
                    webp: '3d-can.webp',
                    webpSp: '3d-can.webp',
                    alt: '3D Demo Can',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Can',
                    day: '2021 / 10 / 25',
                },
                {
                    link: 'https://kaito-takase.dev/3d-physics/',
                    png: '3d-physics.png',
                    pngSp: '3d-physics.png',
                    webp: '3d-physics.webp',
                    webpSp: '3d-physics.webp',
                    alt: '3D Demo Physics',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Physics',
                    day: '2021 / 10 / 24',
                },
                {
                    link: 'https://kaito-takase.dev/3d-halloween/',
                    png: '3d-halloween.png',
                    pngSp: '3d-halloween.png',
                    webp: '3d-halloween.webp',
                    webpSp: '3d-halloween.webp',
                    alt: '3D Demo Halloween',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Halloween',
                    day: '2021 / 10 / 31',
                },
                {
                    link: 'https://kaito-takase.dev/3d-car/',
                    png: '3d-car.png',
                    pngSp: '3d-car.png',
                    webp: '3d-car.webp',
                    webpSp: '3d-car.webp',
                    alt: '3D Demo Key Press Animation',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Key Press Animation',
                    day: '2021 / 10 / 16',
                },
                {
                    link: 'https://kaito-takase.dev/3d-apple/',
                    png: '3d-apple.png',
                    pngSp: '3d-apple.png',
                    webp: '3d-apple.webp',
                    webpSp: '3d-apple.webp',
                    alt: '3D Demo Apple',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Apple',
                    day: '2021 / 10 / 12',
                },
                {
                    link: 'https://kaito-takase.dev/3d-banana/',
                    png: '3d-banana.png',
                    pngSp: '3d-banana.png',
                    webp: '3d-banana.webp',
                    webpSp: '3d-banana.webp',
                    alt: '3D Demo Clone Object',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Clone Object',
                    day: '2021 / 10 / 11',
                },
                {
                    link: 'https://kaito-takase.dev/3d-animation-shadow/',
                    png: '3d-shadow.png',
                    pngSp: '3d-shadow.png',
                    webp: '3d-shadow.webp',
                    webpSp: '3d-shadow.webp',
                    alt: '3D Demo Animation Shadow',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Animation Shadow',
                    day: '2021 / 10 / 11',
                },
                {
                    link: 'https://kaito-takase.dev/menu-hover-effects/',
                    png: 'menu-hover-effects.png',
                    pngSp: 'menu-hover-effects.png',
                    webp: 'menu-hover-effects.webp',
                    webpSp: 'menu-hover-effects.webp',
                    alt: 'Menu Hover Effects',
                    width: 1341,
                    height: 733,
                    title: 'Menu Hover Effects',
                    day: '2021 / 09 / 14',
                },
                {
                    link: 'https://kaito-takase.dev/spy-navigation/',
                    png: 'spy-navigation.png',
                    pngSp: 'spy-navigation.png',
                    webp: 'spy-navigation.webp',
                    webpSp: 'spy-navigation.webp',
                    alt: 'Spy Navigation',
                    width: 1341,
                    height: 733,
                    title: 'Spy Navigation',
                    day: '2021 / 09 / 09',
                },
                {
                    link: 'https://kaito-takase.dev/3d-star/',
                    png: '3d-star.png',
                    pngSp: '3d-star.png',
                    webp: '3d-star.webp',
                    webpSp: '3d-star.webp',
                    alt: '3D Demo Star',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Star',
                    day: '2021 / 09 / 07',
                },
                {
                    link: 'https://kaito-takase.dev/horizontal-smoothscroll/',
                    png: 'HorizontalSmoothScroll.png',
                    pngSp: 'HorizontalSmoothScroll.png',
                    webp: 'HorizontalSmoothScroll.webp',
                    webpSp: 'HorizontalSmoothScroll.webp',
                    alt: 'Horizontal Smooth Scroll',
                    width: 1341,
                    height: 733,
                    title: 'Horizontal Smooth Scroll',
                    day: '2021 / 07 / 26',
                },
                {
                    link: 'https://kaito-takase.dev/scrolling-bent-text/',
                    png: 'bend-text.png',
                    pngSp: 'bend-text.png',
                    webp: 'bend-text.webp',
                    webpSp: 'bend-text.webp',
                    alt: 'Scrolling Bent Text',
                    width: 1341,
                    height: 733,
                    title: 'Scrolling Bent Text',
                    day: '2021 / 07 / 25',
                },
                {
                    link: 'https://kaito-takase.dev/marquee-animation/',
                    png: 'marquee.png',
                    pngSp: 'marquee.png',
                    webp: 'marquee.webp',
                    webpSp: 'marquee.webp',
                    alt: 'Marquee Hover Animation',
                    width: 1341,
                    height: 733,
                    title: 'Marquee Hover Animation',
                    day: '2021 / 07 / 20',
                },
                {
                    link: 'https://kaito-takase.dev/glsl-distortion/',
                    png: 'glsl-distortion.png',
                    pngSp: 'glsl-distortion.png',
                    webp: 'glsl-distortion.webp',
                    webpSp: 'glsl-distortion.webp',
                    alt: 'Demo GLSL DistortionHoverEffect',
                    width: 1341,
                    height: 733,
                    title: 'Demo GLSL DistortionHoverEffect',
                    day: '2021 / 07 / 19',
                },
                {
                    link: 'https://kaito-takase.dev/change-image/',
                    png: 'changeImg.png',
                    pngSp: 'changeImg.png',
                    webp: 'changeImg.webp',
                    webpSp: 'changeImg.webp',
                    alt: 'Demo Change Image',
                    width: 1341,
                    height: 733,
                    title: 'Demo Change Image',
                    day: '2021 / 07 / 16',
                },
                {
                    link: 'https://kaito-takase.dev/distortion-hover-effect/',
                    png: 'hoverEffect.png',
                    pngSp: 'hoverEffect.png',
                    webp: 'hoverEffect.webp',
                    webpSp: 'hoverEffect.webp',
                    alt: 'Demo DistortionHoverEffect',
                    width: 1341,
                    height: 733,
                    title: 'Demo DistortionHoverEffect',
                    day: '2021 / 07 / 15',
                },
                {
                    link: 'https://kaito-takase.dev/3d-animation/',
                    png: '3d-animation.png',
                    pngSp: '3d-animation.png',
                    webp: '3d-animation.webp',
                    webpSp: '3d-animation.webp',
                    alt: '3D Demo Blender Animation',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Blender Animation',
                    day: '2021 / 07 / 13',
                },
                {
                    link: 'https://kaito-takase.dev/3d-watch/',
                    png: 'watch.png',
                    pngSp: 'watch.png',
                    webp: 'watch.webp',
                    webpSp: 'watch.webp',
                    alt: '3D Demo Watch',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Watch',
                    day: '2021 / 06 / 24',
                },
                {
                    link: 'https://kaito-takase.dev/3d-juice/',
                    png: 'juice.png',
                    pngSp: 'juice.png',
                    webp: 'juice.webp',
                    webpSp: 'juice.webp',
                    alt: '3D Demo Juice',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Juice',
                    day: '2021 / 06 / 24',
                },
                {
                    link: 'https://kaito-takase.dev/3d-dice/',
                    png: 'dice.png',
                    pngSp: 'dice.png',
                    webp: 'dice.webp',
                    webpSp: 'dice.webp',
                    alt: '3D Demo Dice',
                    width: 1341,
                    height: 733,
                    title: '3D Demo Dice',
                    day: '2021 / 05 / 11',
                },
                {
                    link: 'https://kaito-takase.dev/header-mouse-hover/',
                    png: '20210412.png',
                    pngSp: '20210412.png',
                    webp: '20210412.webp',
                    webpSp: '20210412.webp',
                    alt: 'Header & Mouse Hover',
                    width: 1341,
                    height: 733,
                    title: 'Header & Mouse Hover',
                    day: '2021 / 04 / 12',
                },
                {
                    link: 'https://kaito-takase.dev/barbajs/page1.html/',
                    png: '20210208.png',
                    pngSp: '20210208.png',
                    webp: '20210208.webp',
                    webpSp: '20210208.webp',
                    alt: 'Barba.js(v2)',
                    width: 1341,
                    height: 733,
                    title: 'Barba.js(v2)',
                    day: '2021 / 02 / 08',
                },
                {
                    link: 'https://kaito-takase.dev/one-scroll/',
                    png: '20210202.png',
                    pngSp: '20210202.png',
                    webp: '20210202.webp',
                    webpSp: '20210202.webp',
                    alt: 'One Scroll',
                    width: 1341,
                    height: 733,
                    title: 'One Scroll',
                    day: '2021 / 02 / 02',
                },
                {
                    link: 'https://kaito-takase.dev/page-transition/',
                    png: 'page_transition.png',
                    pngSp: 'page_transition.png',
                    webp: 'page_transition.webp',
                    webpSp: 'page_transition.webp',
                    alt: 'Page Transition',
                    width: 1341,
                    height: 733,
                    title: 'Page Transition',
                    day: '2021 / 01 / 27',
                },
                {
                    link: 'https://kaito-takase.dev/scroll-interlocking/',
                    png: '20210121.png',
                    pngSp: '20210121.png',
                    webp: '20210121.webp',
                    webpSp: '20210121.webp',
                    alt: 'Scroll Interlocking',
                    width: 1341,
                    height: 733,
                    title: 'Scroll Interlocking',
                    day: '2021 / 01 / 21',
                },
                {
                    link: 'https://kaito-takase.dev/scroll-count-circle/',
                    png: '20210114.png',
                    pngSp: '20210114.png',
                    webp: '20210114.webp',
                    webpSp: '20210114.webp',
                    alt: 'Scroll Count Circle',
                    width: 1341,
                    height: 733,
                    title: 'Scroll Count Circle',
                    day: '2021 / 01 / 13',
                },
                {
                    link: 'https://kaito-takase.dev/scroll-count-bar/',
                    png: '20210113.png',
                    pngSp: '20210113.png',
                    webp: '20210113.webp',
                    webpSp: '20210113.webp',
                    alt: 'Scroll Count Bar',
                    width: 1341,
                    height: 733,
                    title: 'Scroll Count Bar',
                    day: '2021 / 01 / 13',
                },
                {
                    link: 'https://kaito-takase.dev/scroll-image-parallax/',
                    png: 'scroll-image-parallax.png',
                    pngSp: 'scroll-image-parallax.png',
                    webp: 'scroll-image-parallax.webp',
                    webpSp: 'scroll-image-parallax.webp',
                    alt: 'Scroll Image Parallax',
                    width: 1341,
                    height: 733,
                    title: 'Scroll Image Parallax',
                    day: '2021 / 01 / 10',
                },
                {
                    link: 'https://kaito-takase.dev/header-mix-blend-mode/',
                    png: '20210108.png',
                    pngSp: '20210108.png',
                    webp: '20210108.webp',
                    webpSp: '20210108.webp',
                    alt: 'Header & Mix Blend Mode',
                    width: 1341,
                    height: 733,
                    title: 'Header & Mix Blend Mode',
                    day: '2021 / 01 / 08',
                },
                {
                    link: 'https://kaito-takase.dev/20210107/',
                    png: '20210107.png',
                    pngSp: '20210107.png',
                    webp: '20210107.webp',
                    webpSp: '20210107.webp',
                    alt: 'Header',
                    width: 1341,
                    height: 733,
                    title: 'Header',
                    day: '2021 / 01 / 07',
                },
                {
                    link: 'https://kaito-takase.dev/blender-animation/',
                    png: 'blender-animation.png',
                    pngSp: 'blender-animation.png',
                    webp: 'blender-animation.webp',
                    webpSp: 'blender-animation.webp',
                    alt: 'blender-animation',
                    width: 1341,
                    height: 733,
                    title: 'blender-animation',
                    day: '2020 / 12 / 22',
                },
            ],
        };
    },
    mounted() {
        window.addEventListener('scroll', this.scrollWindow);
    },
    methods: {
        returnTop() {
            window.scrollTo({
                top: 0,
                behavior: 'smooth',
            });
        },
        scrollWindow() {
            const top = 200;
            this.scroll = window.scrollY;
            if (top <= this.scroll) {
                this.buttonActive = true;
            } else {
                this.buttonActive = false;
            }
        },
    },
});
</script>
